# Налаштування пам'яті для Gradle (працює і в хмарі GitHub Actions)
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# Обов'язково для сучасних бібліотек Android
android.useAndroidX=true

# Швидша збірка
android.nonTransitiveRClass=true

# Не запускати занадто багато паралельних процесів (економить пам'ять)
org.gradle.workers.max=2
